### ISSUE TITLE
Improve CircleCI error handling

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/openFEC#4935]
### What we’re after

We should separate the build commands in CircleCI so if one fails, the build fails.

By combining the commands with `&&`, if one fails and one passes the build will still pass.
Example:
```
$ echo true && false
true
```

This build should have failed on the `Install system dependencies` step: https://app.circleci.com/pipelines/github/fecgov/openFEC/1067/workflows/c0e3c693-398f-405f-b84c-b99e8c1492d8/jobs/3550

### Related ticket(s)

https://github.com/fecgov/openFEC/issues/4933

### Action item(s)

- [ ] We should separate the build commands in CircleCI so if one fails, the build fails.

**Before**
```
 - run:
          name: Install system dependencies
          # Commands listed here are from the CircleCI PostgreSQL config docs:
          # https://circleci.com/docs/2.0/postgres-config/#postgresql-circleci-configuration-example
          command: |
            sudo apt-get update -qq && sudo apt-get install -y build-essential postgresql-client
            echo 'export PATH=/usr/lib/postgresql/10.11/bin/:$PATH' >> $BASH_ENV
```
**After**
```
 - run:
          name: Install system dependencies
          # Commands listed here are from the CircleCI PostgreSQL config docs:
          # https://circleci.com/docs/2.0/postgres-config/#postgresql-circleci-configuration-example
          command: |
            sudo apt-get update -qq 
            sudo apt-get install -y build-essential postgresql-client
            echo 'export PATH=/usr/lib/postgresql/10.11/bin/:$PATH' >> $BASH_ENV
```

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] Fix openFEC
- [ ] Open up tickets for other repos

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)
